@ECHO OFF
TITLE SuperCMD is updating to 0.0.1...
ECHO SuperCMD is updating... please wait...
ECHO Actual version is 0.0.1
ECHO Downloading the changelog...
wget https://raw.githubusercontent.com/SuperCMD/DotCMD/master/changelog.txt
ECHO Type 'changelog' to see the changelog.
